reddit/config/routes.rb
Rails.application.routes.draw do

  
resources :users, only: [:new,:create]
resource :session, only: [:new,:create,:destroy]
resources :subs, except: [:destroy]
resources :posts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title,presence:true
  

  
  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User
  
  
  has_many :post_subs,inverse_of: :post,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: :PostSub
  
  has_many :subs,
  through: :post_subs,
  source: :sub
  
  
  
end

reddit/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint(8)        not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  belongs_to :post,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: :Post
  
  
  belongs_to :sub,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :Sub
  
end

reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  
  
    
  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :User
  
  has_many :post_subs,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :PostSub
  
  has_many :posts,
  through: :post_subs,
  source: :post
  
  
end

reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length:{minimum:6, allow_nil:true}
  before_validation :ensure_session_token
  attr_reader :password
  
  has_many :posts,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :Post
  
  has_many :subs,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :Sub
  
  
  
  
  
  def ensure_session_token
      self.session_token ||= User.generate_session_token
  end
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && BCrypt::Password.new(self.password_digest).is_password?(password)
    nil
  end
end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :signed_in?
  
  
  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
  end
  
  def signout
    current_user.reset_session_token
    session[:session_token] = nil
  end
  
  def signed_in?
    !!current_user
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def require_sign_in
    redirect_to new_session_url unless signed_in?
  end
  
  
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
  before_action :require_sign_in
    
  def new
    @post = Post.new
    @subjects = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    
    # @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
      @subjects = Sub.all
      @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def index
    @subjects = Sub.all
    @post = Post.all
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end 

end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    if user
      sign_in(user)
      # redirect_to
    else
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
    end
  end
  

  def destroy
    signout
    redirect_to new_session_url
  end
end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_sign_in
  
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.erros.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.erros.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def index
    @sub = Sub.all
  end
  
  private
  
  
  def sub_params
    params.require(:sub).permit(:title,:description)
  end
  
end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  
  private
  
  
  def user_params
    params.require(:user).permit(:username,:password)
  end
  
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
  def token
    "<input 
    type=\"hidden\" 
    name=\"authenticity_token\"
    value=\"#{form_authenticity_token}\">".html_safe
  end
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if signed_in? %>
      Welcome <%= current_user.username  %>! You are logged in!!!  👀
      <br>
      <form action="<%= session_url %>" method="post">
        <%= token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Sign out">
      </form>
      <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Sign In  </a>
      
      
      <% end %>
    <%= yield %>
  </body>
</html>

reddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<form class="" action="<%=post_url(@post)%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= token %>
<label>Title
  <input type="text" name="post[title]" value="<%=@post.title%>">
</label>

<label>URL
  <input type="text" name="post[url]" value="<%=@post.url%>">
</label>

<label>Content
  <input type="text" name="post[content]" value="<%=@post.content%>">
</label>
<input type="hidden" name="post[sub_ids][]" value="">
<% @subjects.each do |sub| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>" <%= "checked" if @post.sub_ids.include?(sub.id) %> >
  <%= sub.title %><br>
  
<%end %>


<input type="submit" name="" value="Edit Post">

</form>

reddit/app/views/posts/index.html.erb
All Posts: <br>

<% @post.each do |post| %>


<label>Title
<%=post.title%>
</label>

<label>URL
  <%=post.url%>
</label>

<label>Content
  <%=post.content%>
</label>

<label>
  Subjects:
  <br>
<% post.subs.each do |subj| %>
<%=subj.title %>
<br>
<% end  %>
</label>

<br>&nbsp<br>
<br>&nbsp<br>
<% end %>

reddit/app/views/posts/new.html.erb
<h1>New Post</h1>
<form class="" action="<%=posts_url%>" method="post">
  <%= token %>
<label>Title
  <input type="text" name="post[title]" value="<%=@post.title%>">
</label>

<label>URL
  <input type="text" name="post[url]" value="<%=@post.url%>">
</label>

<label>Content
  <input type="text" name="post[content]" value="<%=@post.content%>">
</label>
<input type="hidden" name="post[sub_ids][]" value="">
<% @subjects.each do |sub| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>">
  <%= sub.title %><br>
  
<%end %>


<input type="submit" name="" value="Add Post">

</form>

reddit/app/views/posts/show.html.erb
<h1>Show Post</h1>


<label>Title
<%=@post.title%>
</label>

<label>URL
  <%=@post.url%>
</label>

<label>Content
  <%=@post.content%>
</label>
<label>
  Subjects:
  <br>
<% @post.subs.each do |subj| %>
<%=subj.title %>
<br>
<% end  %>
</label>

reddit/app/views/subs/edit.html.erb
<h1>Edit Subject</h1>


<form  action="<%= sub_url(@sub) %>" method="post">
  
  <input type="hidden" name="_method" value="patch">
<%= token  %>


<label for="">
  Title
<input type="text" name="sub[title]" value="<%= @sub.title %>">    
</label>

<label for="">
  Description
<input type="text" name="sub[description]" value="<%= @sub.description %>">    
</label>

<input type="submit" name="" value="Update Subject">
  
</form>

reddit/app/views/subs/index.html.erb
<a href="<%= new_sub_url  %>">Add new subject</a>&nbsp
<br> &nbsp<br>
<%@sub.each do |sub| %>
<label>Moderator: 
  <%=sub.moderator.username%>
</label><br>


<label for=""><a href="<%=sub_url(sub)%>">
  Title
<%= sub.title %> </a>
</label><br>

<label for="">
  Description
<%= sub.description %>"
</label>
<br> &nbsp<br>
<%end %>

reddit/app/views/subs/new.html.erb
<h1>New Subject</h1>


<form  action="<%= subs_url %>" method="post">
  
<%= token  %>

<label for="">
  Title
<input type="text" name="sub[title]" value="<%= @sub.title %>">    
</label>

<label for="">
  Description
<input type="text" name="sub[description]" value="<%= @sub.description %>">    
</label>

<input type="submit" name="" value="Add Subject">
  
</form>

reddit/app/views/subs/show.html.erb
<a href="<%= subs_url %>"> Back to all subjects</a><br>&nbsp<br>

Subject Info:<br>&nbsp<br>

<label>Moderator: 
  <%=@sub.moderator.username%>
</label><br>


<label for=""><a href="<%=edit_sub_url(@sub)%>">
  Title
<%= @sub.title %> </a>
</label><br>

<label for="">
  Description
<%= @sub.description %>"
</label>

reddit/app/views/users/new.html.erb
<h1>Sign Up page</h1>


<form  action="<%= users_url %>" method="post">
  <%= token  %>
  <label for="">
    Username:
    <input type="text" name="user[username]" value="<%=@user.username%>">
  
  </label>
  
  <label for="">
    Password:
    <input type="password" name="user[password]" value="<%=@user.password%>">
  
  </label>
  
  
  <input type="submit" name="" value="Sign Up">
  
  
  
</form>